# Pandas challenges

Read the `veahicles.csv` dataframe and store it in a variable called `cars`:

In [213]:
# code here

import pandas as pd

cars = pd.read_csv('data/vehicles.csv')
print(cars)

                   Make                Model  Year  Engine Displacement  \
0            AM General    DJ Po Vehicle 2WD  1984                  2.5
1            AM General     FJ8c Post Office  1984                  4.2
2            AM General  Post Office DJ5 2WD  1985                  2.5
3            AM General  Post Office DJ8 2WD  1985                  4.2
4      ASC Incorporated                  GNX  1987                  3.8
...                 ...                  ...   ...                  ...
35947             smart         fortwo coupe  2013                  1.0
35948             smart         fortwo coupe  2014                  1.0
35949             smart         fortwo coupe  2015                  1.0
35950             smart         fortwo coupe  2016                  0.9
35951             smart         fortwo coupe  2016                  0.9

       Cylinders     Transmission        Drivetrain  \
0            4.0  Automatic 3-spd     2-Wheel Drive
1            6.0  Automatic 3-spd     2-Wheel Drive
2            4.0  Automatic 3-spd  Rear-Wheel Drive
3            6.0  Automatic 3-spd  Rear-Wheel Drive
4            6.0  Automatic 4-spd  Rear-Wheel Drive
...          ...              ...               ...
35947        3.0        Auto(AM5)  Rear-Wheel Drive
35948        3.0        Auto(AM5)  Rear-Wheel Drive
35949        3.0        Auto(AM5)  Rear-Wheel Drive
35950        3.0        Auto(AM6)  Rear-Wheel Drive
35951        3.0     Manual 5-spd  Rear-Wheel Drive

                     Vehicle Class Fuel Type  Fuel Barrels/Year  City MPG  \
0      Special Purpose Vehicle 2WD   Regular          19.388824        18
1      Special Purpose Vehicle 2WD   Regular          25.354615        13
2      Special Purpose Vehicle 2WD   Regular          20.600625        16
3      Special Purpose Vehicle 2WD   Regular          25.354615        13
4                     Midsize Cars   Premium          20.600625        14
...                            ...       ...                ...       ...
35947                  Two Seaters   Premium           9.155833        34
35948                  Two Seaters   Premium           9.155833        34
35949                  Two Seaters   Premium           9.155833        34
35950                  Two Seaters   Premium           9.155833        34
35951                  Two Seaters   Premium           9.417429        32

       Highway MPG  Combined MPG  CO2 Emission Grams/Mile  Fuel Cost/Year
0               17            17               522.764706            1950
1               13            13               683.615385            2550
2               17            16               555.437500            2100
3               13            13               683.615385            2550
4               21            16               555.437500            2550
...            ...           ...                      ...             ...
35947           38            36               244.000000            1100
35948           38            36               243.000000            1100
35949           38            36               244.000000            1100
35950           39            36               246.000000            1100
35951           39            35               255.000000            1150

[35952 rows x 15 columns]

Explore the dataset:

- How many rows and columns are there?

- What are the data types of the columns?

- Are there missing values?

- What are the ranges / distributions of the numerical columns?

- What are the value counts for the categorical columns?

In [147]:
# code here

#Answer 1
#cars.info()

#Answer 2
#print(cars.dtypes)

#Answer 3
#cars.isnull()
#print(cars.isnull())

#NO missing values

#Answer 4
#cars.describe(include=[np.number])

#Answer 5

#To check if it's a categorical column
#there are 6 categorical columns
#Make,Model,Year,Drivetrain,Vehicle Class,Fuel Type 

#print(cars.Make.value_counts())
#print(cars.Model.value_counts())
#print(cars.Year.value_counts())
#print(cars.Drivetrain.value_counts())
#print(cars.Year.value_counts())

In [71]:
cars.drop('Combined MPG', axis=1)

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,522.764706,1950
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,683.615385,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,555.437500,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,683.615385,2550
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,555.437500,2550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,smart,fortwo coupe,2013,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,244.000000,1100
35948,smart,fortwo coupe,2014,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,243.000000,1100
35949,smart,fortwo coupe,2015,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,244.000000,1100
35950,smart,fortwo coupe,2016,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,39,246.000000,1100
35951,smart,fortwo coupe,2016,0.9,3.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,32,39,255.000000,1150

Drop the column "Combined MPG"

In [80]:
# code here

#cars.columns=cars.columns.str.replace(' ','')
#cars.columns=cars.columns.str.replace('/','Per')
#cars.head()

,Make,Model,Year,EngineDisplacement,Cylinders,Transmission,Drivetrain,VehicleClass,FuelType,FuelBarrelsPerYear,CityMPG,HighwayMPG,CombinedMPG,CO2EmissionGramsPerMile,FuelCostPerYear
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550

Change column names so that there are no names with spaces or weird special characters:

In [95]:
# code here
#most_cars = (cars.Make.value_counts())
#print((most_cars))

Chevrolet                             3643
Ford                                  2946
Dodge                                 2360
GMC                                   2347
Toyota                                1836
                                      ...
Excalibur Autos                          1
S and S Coach Company  E.p. Dutton       1
Environmental Rsch and Devp Corp         1
E. P. Dutton, Inc.                       1
Lambda Control Systems                   1
Name: Make, Length: 127, dtype: int64

What brand has the most cars?

In [122]:
# code here

#worse = cars.groupby('Make')['CO2EmissionGramsPerMile'].mean()
#a=worse.sort_values(ascending = False)
#print(a)

Make
Vector                                1049.159722
Superior Coaches Div E.p. Dutton       888.700000
S and S Coach Company  E.p. Dutton     888.700000
Bugatti                                873.062500
Laforza Automobile Inc                 807.909091
                                         ...
MINI                                   313.716862
Daihatsu                               310.188060
Fiat                                   304.666560
smart                                  247.030556
Fisker                                 169.000000
Name: CO2EmissionGramsPerMile, Length: 127, dtype: float64

What brand has the worse CO2 Emissions on average?

In [133]:
# code here
#b=worse.sort_values()
#print(b)

Make
Fisker                                 169.000000
smart                                  247.030556
Fiat                                   304.666560
Daihatsu                               310.188060
MINI                                   313.716862
                                         ...
Laforza Automobile Inc                 807.909091
Bugatti                                873.062500
Superior Coaches Div E.p. Dutton       888.700000
S and S Coach Company  E.p. Dutton     888.700000
Vector                                1049.159722
Name: CO2EmissionGramsPerMile, Length: 127, dtype: float64

Which brands are more environment friendly?

In [ ]:
# code here
#b=worse.sort_values()
#print(b)

Create 4 groups (bins) of cars, by Year. We want to explore how cars have evolved decade by decade.

In [138]:
# code here
#year_grp = cars.groupby('Year').count()


#year_grp = cars.groupby(cars.index.Year).sum().head()
#cars.groupby(cars.index.year)
#print(year_grp)

Did cars consume more gas in the eighties?

In [156]:
# code here

Do cars with automatic transmission consume more fuel than cars with manual transmission?

In [155]:
# code here
# in the next notebook, we will learn how we can clean the "Trans" column

manual=cars.loc[cars['Transmission'] == cars.Transmission.str.contains('Man.')]
automatic=cars.loc[cars['Transmission'] == cars.Transmission.str.contains('Auto.')]
print(manual, automatic)

Empty DataFrame
Columns: [Make, Model, Year, EngineDisplacement, Cylinders, Transmission, Drivetrain, VehicleClass, FuelType, FuelBarrelsPerYear, CityMPG, HighwayMPG, CombinedMPG, CO2EmissionGramsPerMile, FuelCostPerYear]
Index: [] Empty DataFrame
Columns: [Make, Model, Year, EngineDisplacement, Cylinders, Transmission, Drivetrain, VehicleClass, FuelType, FuelBarrelsPerYear, CityMPG, HighwayMPG, CombinedMPG, CO2EmissionGramsPerMile, FuelCostPerYear]
Index: []

Group cars by fuel type and aggregate them by the following criteria: 

- The maximum number cylinders
- The oldest year
- The average Miles Per Gallon in the city

In [149]:
# code here

#Fuel_t = cars.groupby('FuelType')
#print(Fuel_t)

#The maximum number cylinders

maximum = cars.groupby('FuelType').Cylinders.max
print(maximum)

#The oldest year

minimum = cars.groupby('FuelType').Year.min
print(minimum)

#The average Miles Per Gallon in the city

<bound method GroupBy.max of <pandas.core.groupby.generic.SeriesGroupBy object at 0x00000183457A4940>>
<bound method GroupBy.min of <pandas.core.groupby.generic.SeriesGroupBy object at 0x0000018344C91280>>

We want to use "Drivetrain" in a statistical model. Convert the column to numeric.

In [214]:
# code here

#x = x.replace("-"," ")

#Dt_modify = cars.groupby('Drivetrain').sum()
#print(Dt_modify)

#another method for replacing single value:
#cars['Drivetrain'] = cars['Drivetrain'].str.replace('2-Wheel Drive, Front','2')


cars['Drivetrain'] = cars.Drivetrain.map({'2-Wheel Drive, Front':2,'Rear-Wheel Drive':8,'4-Wheel or All-Wheel Drive':4,'Part-time 4-Wheel Drive':7,'2-Wheel Drive':1,'4-Wheel Drive':3,'All-Wheel Drive':5,'Front-Wheel Drive':6})
cars.head(5)

#cars['Drivetrain'] = pd.to_numeric(cars['Drivetrain'])
#cars.head(5)

#cars[["Drivetrain"]] = cars[["Drivetrain"]].apply(pd.to_numeric)
#cars.head(5)

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,1,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,1,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,8,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,8,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,8,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550

Read the `car_brands.csv` data:

In [172]:
# code here

car_brands = pd.read_csv('data/car_brands.csv')

Join the cars dataframe with the car brands dataframe.

In [186]:
# code here

joined = cars.join(car_brands.set_index('brand'), on='Make')
joined.head(10)

,Make,Model,Year,EngineDisplacement,Cylinders,Transmission,Drivetrain,VehicleClass,FuelType,FuelBarrelsPerYear,CityMPG,HighwayMPG,CombinedMPG,CO2EmissionGramsPerMile,FuelCostPerYear,revenue,production
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950,1537,1.002916
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550,1537,1.002916
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100,1537,1.002916
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550,1537,1.002916
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550,232,1.628105
5,Acura,2.2CL/3.0CL,1997,2.2,4.0,Automatic 4-spd,Front-Wheel Drive,Subcompact Cars,Regular,14.982273,20,26,22,403.954545,1500,234,3.394481
6,Acura,2.2CL/3.0CL,1997,2.2,4.0,Manual 5-spd,Front-Wheel Drive,Subcompact Cars,Regular,13.733750,22,28,24,370.291667,1400,234,3.394481
7,Acura,2.2CL/3.0CL,1997,3.0,6.0,Automatic 4-spd,Front-Wheel Drive,Subcompact Cars,Regular,16.480500,18,26,20,444.350000,1650,234,3.394481
8,Acura,2.3CL/3.0CL,1998,2.3,4.0,Automatic 4-spd,Front-Wheel Drive,Subcompact Cars,Regular,14.982273,19,27,22,403.954545,1500,234,3.394481
9,Acura,2.3CL/3.0CL,1998,2.3,4.0,Manual 5-spd,Front-Wheel Drive,Subcompact Cars,Regular,13.733750,21,29,24,370.291667,1400,234,3.394481

Which brands have the most revenue?

In [189]:
# code here
#revenue = (cars.Make.value_counts())

#revenue = car_brands.groupby('brand')['revenue'].sum()
#a=revenue.sort_values(ascending = False)
#print(a)

revenue = joined.groupby('Make')['revenue'].max()
a=revenue.sort_values(ascending = False)
print(a)

Make
Geo                            1988.0
Volga Associated Automobile    1965.0
Goldacre                       1958.0
Ferrari                        1946.0
CX Automotive                  1935.0
                                ...
Lotus                            45.0
Cadillac                         42.0
Pontiac                          31.0
PAS Inc - GMC                    22.0
Audi                             18.0
Name: revenue, Length: 127, dtype: float64